set imap_user = "matt.vilim@gmail.com"
set smtp_url = "smtp://matt.vilim@smtp.gmail.com:587/"
set from = "matt.vilim@gmail.com"
set realname = "Matthew Vilim"
set folder = "imaps://imap.gmail.com:993"
set spoolfile = "+INBOX"
set postponed="+Drafts"
